export const PATRON_ACTIONS = {
    PGET: 'PGET',
    PSTORE: 'PSTORE',
    CHECK_IN: 'CHECK_IN',
    CHECK_OUT: 'CHECK_OUT',
    SEARCH: 'SEARCH',
    STORE_SEARCH_RESULTS: 'STORE_SEARCH_RESULTS',
    ADD_FRIEND: 'ADD_FRIEND',
    FETCH_CHECKINS: 'FETCH_CHECKINS',
    STORE_CHECKINS: 'STORE_CHECKINS',
};